[build]
  command = "npm run build"
  publish = "dist"

# Disable plugins that might be causing issues
[build.environment]
  SKIP_PLUGINS = "true"

[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
