[build]
  command = "npm ci && npm run build"
  publish = "dist"
  base = "luvlang.org"

[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
