providers = ['node']

[variables]
NODE_ENV = 'production'

[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm-9_x']

[phases.install]  
cmds = ['npm ci', 'cd luvlang.org && npm ci && npm run build']

[phases.build]
cmds = ['echo "No build step needed for Node.js server"']

[start]
cmd = 'node server-fullstack.js'