providers = ['node']

[variables]
NODE_ENV = 'production'

[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm-9_x']

[phases.install]  
cmds = ['cd railway-deploy && npm ci']

[phases.build]
cmds = ['echo "No build step needed for Node.js server"']

[start]
cmd = 'cd railway-deploy && node server.js'