[variables]
NIXPACKS_NO_DEFAULT_CACHE_DIR = '1'

[providers]
node = true

[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm']

[phases.install]  
cmds = ['cd railway-deploy && npm ci']

[start]
cmd = 'cd railway-deploy && node server.js'