providers = ['node']

[variables]
NODE_ENV = 'production'

[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm-9_x']

[phases.install]  
cmds = ['rm -f package-lock.json', 'npm install --production']

[phases.build]
cmds = ['cp -r dist public 2>/dev/null || echo "Using existing build"']

[start]
cmd = 'node server-fullstack.js'