providers = ['node']

[variables]
NODE_ENV = 'production'

[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm-9_x']

[phases.install]  
cmds = ['npm ci']

[phases.build]
cmds = ['cp -r luvlang.org/dist ./public 2>/dev/null || echo "Using existing build"']

[start]
cmd = 'node server-fullstack.js'